### ISSUE TITLE
facebook page in iframe

### ISSUE THREAD

**Issue by akarsh** [gdg-berlin-android/gdg-berlin-android.github.io#9]
Here is the iframe for facebook
`<iframe src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2FGDGBerlinAndroid&tabs=timeline&width=340&height=500&small_header=true&adapt_container_width=true&hide_cover=true&show_facepile=true&appId" width="340" height="500" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>`

**Comment by cketti** [comment]
Thanks for your suggestion. But showing the Facebook page in an iframe is not something we want to do.
